namespace LeDormeur.Localization;

/// <summary>
/// All UI strings for supported languages.
/// </summary>
public sealed class UiStrings
{
    public required string WindowTitle { get; init; }
    public required string AppTitle { get; init; }
    public required string DurationLabel { get; init; }
    public required string HoursUnit { get; init; }
    public required string MinutesUnit { get; init; }
    public required string BrightnessLabel { get; init; }
    public required string Start { get; init; }
    public required string Cancel { get; init; }
    public required string Ready { get; init; }
    public required string LanguageLabel { get; init; }
    public required string ModeDetecting { get; init; }
    public required string ModeWmi { get; init; }
    public required string ModeGamma { get; init; }
    public required string ModeGammaUnavailable { get; init; }
    public required string BrightnessControlFailedTitle { get; init; }
    public required string BrightnessControlFailedMessage { get; init; }
    public required string BrightnessControlFailedStatus { get; init; }
    public required string InvalidDurationTitle { get; init; }
    public required string InvalidDurationMessage { get; init; }
    public required string Cancelled { get; init; }
    public required string TimeElapsedSleeping { get; init; }
    public required string SleepingPc { get; init; }
    public required string SleepFailedTitle { get; init; }
    public required string SleepFailedMessage { get; init; }
    public required string SleepFailedStatus { get; init; }
    public required string SleepOkStatus { get; init; }
    public required string BrightnessRestoredAfterWake { get; init; }
    public required string SleepFailedStatusRestored { get; init; }
    public required string RunningStatus { get; init; }
    public required string Remaining { get; init; }
    public required string QuitTitle { get; init; }
    public required string QuitMessage { get; init; }

    /// <summary>
    /// {0} = percent, {1} = duration text, {2} = start brightness, {3} = end brightness
    /// </summary>
    public required string ExampleHint { get; init; }

    public required string DurationHoursOnly { get; init; }
    public required string DurationMinutesOnly { get; init; }
    public required string DurationHoursAndMinutes { get; init; }
    public required string DurationZero { get; init; }

    public required string WarningTitle { get; init; }
    /// <summary>{0} = remaining seconds</summary>
    public required string WarningCountdown { get; init; }
    public required string WarningHint { get; init; }
    public required string WarningPostpone { get; init; }
    public required string WarningCancel { get; init; }
    public required string WarningContinue { get; init; }
    public required string PostponedStatus { get; init; }

    public required string TrayOpen { get; init; }
    public required string TrayCancel { get; init; }
    public required string TrayExit { get; init; }
    public required string TrayIdle { get; init; }
    /// <summary>{0} = HH:MM:SS remaining</summary>
    public required string TrayRunning { get; init; }
    public required string TrayMinimizedBalloonTitle { get; init; }
    public required string TrayMinimizedBalloonText { get; init; }
    public required string TrayAutoMode { get; init; }
    /// <summary>{0} = HH:mm schedule</summary>
    public required string TrayAutoArmed { get; init; }

    public required string AutoModeButton { get; init; }
    public required string AutoModeWindowTitle { get; init; }
    public required string AutoModeTitle { get; init; }
    public required string AutoModeEnable { get; init; }
    public required string AutoModeTime { get; init; }
    public required string AutoModeTimeout { get; init; }
    public required string AutoModeTimeoutUnit { get; init; }
    public required string AutoModeHint { get; init; }
    public required string AutoModeSave { get; init; }
    public required string AutoModeCancel { get; init; }
    public required string AutoModeDisabledStatus { get; init; }
    /// <summary>{0} = HH:mm, {1} = timeout minutes</summary>
    public required string AutoModeNextStatus { get; init; }
    public required string AutoModeArmedStatus { get; init; }
    public required string AutoModeStillHereStatus { get; init; }
    public required string AutoModeSleepingStatus { get; init; }

    public required string StillThereTitle { get; init; }
    public required string StillThereMessage { get; init; }
    /// <summary>{0} = minutes, {1} = seconds</summary>
    public required string StillThereCountdown { get; init; }
    public required string StillThereYes { get; init; }
    public required string StillThereBalloonTitle { get; init; }
    public required string StillThereBalloonText { get; init; }

    public required string OptionsButton { get; init; }
    public required string TrayOptions { get; init; }
    public required string OptionsWindowTitle { get; init; }
    public required string OptionsTitle { get; init; }
    /// <summary>{0} = active power plan friendly name</summary>
    public required string OptionsPowerPlan { get; init; }
    public required string OptionsPowerPlanUnknown { get; init; }
    public required string OptionsWakeTimersLabel { get; init; }
    public required string OptionsOn { get; init; }
    public required string OptionsOff { get; init; }
    public required string OptionsWakeTimersHint { get; init; }
    public required string OptionsWakeTimersOnStatus { get; init; }
    public required string OptionsWakeTimersOffStatus { get; init; }
    public required string OptionsWakeTimersReadFailed { get; init; }
    public required string OptionsWakeTimersWriteFailed { get; init; }
    public required string OptionsWakeTimersWriteFailedAdmin { get; init; }
    public required string OptionsSave { get; init; }
    public required string OptionsCancel { get; init; }
    public required string OptionsWakeOnLanLabel { get; init; }
    public required string OptionsWakeOnLanHint { get; init; }
    public required string OptionsWakeOnLanUnsupported { get; init; }
    public required string OptionsLastWakeSection { get; init; }
    public required string OptionsLastWakeUnknown { get; init; }
    /// <summary>{0} = wake source</summary>
    public required string OptionsLastWakeValue { get; init; }
    /// <summary>{0} = wake source, {1} = local date/time</summary>
    public required string OptionsLastWakeValueAt { get; init; }
    public required string OptionsLastWakeRefresh { get; init; }
    public required string OptionsDevicesSection { get; init; }
    public required string OptionsDevicesHint { get; init; }
    public required string OptionsDevicesEmpty { get; init; }
    public required string OptionsDevicesReadFailed { get; init; }
    public required string OptionsSomeSettingsFailed { get; init; }

    public required string AlreadyRunningTitle { get; init; }
    public required string AlreadyRunningMessage { get; init; }

    public static UiStrings For(AppLanguage language) => language switch
    {
        AppLanguage.English => English,
        AppLanguage.Spanish => Spanish,
        AppLanguage.German => German,
        AppLanguage.Italian => Italian,
        AppLanguage.Portuguese => Portuguese,
        AppLanguage.Dutch => Dutch,
        AppLanguage.Russian => Russian,
        AppLanguage.Chinese => Chinese,
        _ => French
    };

    public static readonly UiStrings French = new()
    {
        WindowTitle = "Le Dormeur — luminosité + veille",
        AppTitle = "Le Dormeur",
        DurationLabel = "Durée avant la mise en veille",
        HoursUnit = "heure(s)",
        MinutesUnit = "minute(s)",
        BrightnessLabel = "Luminosité à enlever sur cette durée (%)",
        Start = "Démarrer",
        Cancel = "Annuler",
        Ready = "Prêt.",
        LanguageLabel = "Langue",
        ModeDetecting = "Mode luminosité : détection...",
        ModeWmi = "Mode luminosité : matériel (WMI) — luminosité système réelle.",
        ModeGamma = "Mode luminosité : gamma logiciel (écran externe / WMI indisponible).",
        ModeGammaUnavailable = "Mode luminosité : gamma indisponible (HDR / pilote / affichage non supporté).",
        BrightnessControlFailedTitle = "Luminosité indisponible",
        BrightnessControlFailedMessage = "Impossible de baisser la luminosité. En mode gamma, désactive le HDR ou le mode Nuit, vérifie le pilote graphique, ou utilise un écran compatible.",
        BrightnessControlFailedStatus = "Échec du contrôle de luminosité.",
        InvalidDurationTitle = "Durée invalide",
        InvalidDurationMessage = "La durée doit être d’au moins 1 minute.",
        Cancelled = "Annulé. Luminosité restaurée.",
        TimeElapsedSleeping = "Temps écoulé — mise en veille...",
        SleepingPc = "Mise en veille du PC...",
        SleepFailedTitle = "Erreur",
        SleepFailedMessage = "Impossible de forcer la mise en veille. Vérifie les droits ou les paramètres d’alimentation Windows.",
        SleepFailedStatus = "Échec de la mise en veille.",
        SleepOkStatus = "PC mis en veille.",
        BrightnessRestoredAfterWake = "Réveil détecté. Luminosité restaurée au niveau de départ ({0} %).",
        SleepFailedStatusRestored = "Échec de la mise en veille. Luminosité restaurée.",
        RunningStatus = "En cours... Luminosité : {0} % (départ {1} % → cible {2} %)",
        Remaining = "Temps restant : {0}",
        QuitTitle = "Quitter",
        QuitMessage = "Un timer est en cours. Annuler et restaurer la luminosité ?",
        ExampleHint = "Exemple : {0} % sur {1} → à partir de {2} %, la luminosité baissera progressivement jusqu’à environ {3} %, puis le PC se mettra en veille.",
        DurationHoursOnly = "{0} h",
        DurationMinutesOnly = "{0} min",
        DurationHoursAndMinutes = "{0} h {1} min",
        DurationZero = "0 min",
        WarningTitle = "Mise en veille imminente",
        WarningCountdown = "Mise en veille dans {0} s",
        WarningHint = "Reporter ajoute 15 minutes. Annuler stoppe le timer et restaure la luminosité.",
        WarningPostpone = "Reporter (+15 min)",
        WarningCancel = "Annuler",
        WarningContinue = "Continuer",
        PostponedStatus = "Veille reportée de 15 min. Luminosité maintenue, timer relancé.",
        TrayOpen = "Ouvrir",
        TrayCancel = "Annuler le timer",
        TrayExit = "Quitter",
        TrayIdle = "Le Dormeur — prêt",
        TrayRunning = "Le Dormeur — restant {0}",
        TrayMinimizedBalloonTitle = "Le Dormeur",
        TrayMinimizedBalloonText = "L’application continue en arrière-plan.",
        TrayAutoMode = "Mode automatique...",
        TrayAutoArmed = "Le Dormeur — auto {0}",
        AutoModeButton = "Mode auto...",
        AutoModeWindowTitle = "Mode automatique",
        AutoModeTitle = "Mode automatique",
        AutoModeEnable = "Activer le mode automatique",
        AutoModeTime = "Heure de vérification",
        AutoModeTimeout = "Délai de réponse",
        AutoModeTimeoutUnit = "minute(s)",
        AutoModeHint = "À l’heure choisie, une notification demande si vous êtes toujours là. Sans réponse avant la fin du délai, le PC se met en veille.",
        AutoModeSave = "Enregistrer",
        AutoModeCancel = "Fermer",
        AutoModeDisabledStatus = "Mode automatique désactivé.",
        AutoModeNextStatus = "Tous les jours à {0} — délai de réponse : {1} min",
        AutoModeArmedStatus = "Mode auto activé — prochaine vérif. à {0}.",
        AutoModeStillHereStatus = "Présence confirmée. Veille automatique annulée pour aujourd’hui.",
        AutoModeSleepingStatus = "Pas de réponse — mise en veille (mode auto)...",
        StillThereTitle = "Êtes-vous toujours là ?",
        StillThereMessage = "Confirmez votre présence pour éviter la mise en veille automatique.",
        StillThereCountdown = "Veille dans {0:D2}:{1:D2}",
        StillThereYes = "Oui, je suis là",
        StillThereBalloonTitle = "Le Dormeur",
        StillThereBalloonText = "Êtes-vous toujours là ? Répondez pour éviter la veille.",
        OptionsButton = "Options...",
        TrayOptions = "Options...",
        OptionsWindowTitle = "Options",
        OptionsTitle = "Options",
        OptionsPowerPlan = "Profil d’alimentation : {0}",
        OptionsPowerPlanUnknown = "Profil d’alimentation actuel",
        OptionsWakeTimersLabel = "Minuteurs de sortie de veille",
        OptionsOn = "ON",
        OptionsOff = "OFF",
        OptionsWakeTimersHint = "Autorise Windows, les mises à jour et les tâches planifiées à réveiller le PC (profil actuel, secteur et batterie).",
        OptionsWakeTimersOnStatus = "ON — le PC peut être réveillé par des minuteurs.",
        OptionsWakeTimersOffStatus = "OFF — le PC reste en veille.",
        OptionsWakeTimersReadFailed = "Impossible de lire le paramètre du profil d’alimentation.",
        OptionsWakeTimersWriteFailed = "Impossible de modifier le paramètre. Vérifie les droits Windows.",
        OptionsWakeTimersWriteFailedAdmin = "Impossible de modifier le paramètre. Essaie de lancer Le Dormeur en tant qu’administrateur.",
        OptionsSave = "Enregistrer",
        OptionsCancel = "Fermer",
        OptionsWakeOnLanLabel = "Wake-on-LAN",
        OptionsWakeOnLanHint = "Autorise un paquet magique réseau à réveiller le PC (cartes Ethernet).",
        OptionsWakeOnLanUnsupported = "Wake-on-LAN non pris en charge sur ce PC.",
        OptionsLastWakeSection = "Dernier réveil",
        OptionsLastWakeUnknown = "Aucun réveil enregistré.",
        OptionsLastWakeValue = "Réveillé par : {0}",
        OptionsLastWakeValueAt = "Réveillé par : {0} — {1}",
        OptionsLastWakeRefresh = "Actualiser",
        OptionsDevicesSection = "Périphériques autorisés à réveiller le PC",
        OptionsDevicesHint = "Décochez un périphérique pour l’empêcher de réveiller le PC.",
        OptionsDevicesEmpty = "Aucun périphérique configurable trouvé.",
        OptionsDevicesReadFailed = "Impossible de lister les périphériques.",
        OptionsSomeSettingsFailed = "Certains paramètres n’ont pas pu être enregistrés.",
        AlreadyRunningTitle = "Le Dormeur",
        AlreadyRunningMessage = "Le Dormeur est déjà en cours d’exécution."
    };

    public static readonly UiStrings English = new()
    {
        WindowTitle = "Le Dormeur — brightness + sleep",
        AppTitle = "Le Dormeur",
        DurationLabel = "Duration before sleep",
        HoursUnit = "hour(s)",
        MinutesUnit = "minute(s)",
        BrightnessLabel = "Brightness to remove over this duration (%)",
        Start = "Start",
        Cancel = "Cancel",
        Ready = "Ready.",
        LanguageLabel = "Language",
        ModeDetecting = "Brightness mode: detecting...",
        ModeWmi = "Brightness mode: hardware (WMI) — real system brightness.",
        ModeGamma = "Brightness mode: software gamma (external display / WMI unavailable).",
        ModeGammaUnavailable = "Brightness mode: gamma unavailable (HDR / driver / unsupported display).",
        BrightnessControlFailedTitle = "Brightness unavailable",
        BrightnessControlFailedMessage = "Could not reduce brightness. In gamma mode, turn off HDR or Night Light, check your graphics driver, or use a supported display.",
        BrightnessControlFailedStatus = "Brightness control failed.",
        InvalidDurationTitle = "Invalid duration",
        InvalidDurationMessage = "Duration must be at least 1 minute.",
        Cancelled = "Cancelled. Brightness restored.",
        TimeElapsedSleeping = "Time is up — going to sleep...",
        SleepingPc = "Putting the PC to sleep...",
        SleepFailedTitle = "Error",
        SleepFailedMessage = "Could not force sleep. Check permissions or Windows power settings.",
        SleepFailedStatus = "Failed to put the PC to sleep.",
        SleepOkStatus = "PC put to sleep.",
        BrightnessRestoredAfterWake = "Wake detected. Brightness restored to start level ({0} %).",
        SleepFailedStatusRestored = "Failed to put the PC to sleep. Brightness restored.",
        RunningStatus = "Running... Brightness: {0} % (start {1} % → target {2} %)",
        Remaining = "Time remaining: {0}",
        QuitTitle = "Quit",
        QuitMessage = "A timer is running. Cancel and restore brightness?",
        ExampleHint = "Example: {0} % over {1} → from {2} %, brightness will gradually drop to about {3} %, then the PC will sleep.",
        DurationHoursOnly = "{0} h",
        DurationMinutesOnly = "{0} min",
        DurationHoursAndMinutes = "{0} h {1} min",
        DurationZero = "0 min",
        WarningTitle = "Sleep coming up",
        WarningCountdown = "Sleeping in {0} s",
        WarningHint = "Postpone adds 15 minutes. Cancel stops the timer and restores brightness.",
        WarningPostpone = "Postpone (+15 min)",
        WarningCancel = "Cancel",
        WarningContinue = "Continue",
        PostponedStatus = "Sleep postponed by 15 min. Brightness held, timer extended.",
        TrayOpen = "Open",
        TrayCancel = "Cancel timer",
        TrayExit = "Exit",
        TrayIdle = "Le Dormeur — ready",
        TrayRunning = "Le Dormeur — remaining {0}",
        TrayMinimizedBalloonTitle = "Le Dormeur",
        TrayMinimizedBalloonText = "The app is still running in the background.",
        TrayAutoMode = "Automatic mode...",
        TrayAutoArmed = "Le Dormeur — auto {0}",
        AutoModeButton = "Auto mode...",
        AutoModeWindowTitle = "Automatic mode",
        AutoModeTitle = "Automatic mode",
        AutoModeEnable = "Enable automatic mode",
        AutoModeTime = "Check time",
        AutoModeTimeout = "Response timeout",
        AutoModeTimeoutUnit = "minute(s)",
        AutoModeHint = "At the chosen time, a notification asks if you are still there. If you do not answer before the timeout, the PC goes to sleep.",
        AutoModeSave = "Save",
        AutoModeCancel = "Close",
        AutoModeDisabledStatus = "Automatic mode is off.",
        AutoModeNextStatus = "Every day at {0} — response timeout: {1} min",
        AutoModeArmedStatus = "Auto mode on — next check at {0}.",
        AutoModeStillHereStatus = "Presence confirmed. Automatic sleep cancelled for today.",
        AutoModeSleepingStatus = "No response — going to sleep (auto mode)...",
        StillThereTitle = "Are you still there?",
        StillThereMessage = "Confirm you are still here to prevent automatic sleep.",
        StillThereCountdown = "Sleep in {0:D2}:{1:D2}",
        StillThereYes = "Yes, I'm here",
        StillThereBalloonTitle = "Le Dormeur",
        StillThereBalloonText = "Are you still there? Answer to prevent sleep.",
        OptionsButton = "Options...",
        TrayOptions = "Options...",
        OptionsWindowTitle = "Options",
        OptionsTitle = "Options",
        OptionsPowerPlan = "Power plan: {0}",
        OptionsPowerPlanUnknown = "Current power plan",
        OptionsWakeTimersLabel = "Wake timers",
        OptionsOn = "ON",
        OptionsOff = "OFF",
        OptionsWakeTimersHint = "Allows Windows, updates, and scheduled tasks to wake the PC (current plan, plugged in and on battery).",
        OptionsWakeTimersOnStatus = "ON — the PC can be woken by timers.",
        OptionsWakeTimersOffStatus = "OFF — the PC stays asleep.",
        OptionsWakeTimersReadFailed = "Could not read the power plan setting.",
        OptionsWakeTimersWriteFailed = "Could not change the setting. Check Windows permissions.",
        OptionsWakeTimersWriteFailedAdmin = "Could not change the setting. Try running Le Dormeur as administrator.",
        OptionsSave = "Save",
        OptionsCancel = "Close",
        OptionsWakeOnLanLabel = "Wake-on-LAN",
        OptionsWakeOnLanHint = "Allows a magic network packet to wake the PC (Ethernet adapters).",
        OptionsWakeOnLanUnsupported = "Wake-on-LAN is not supported on this PC.",
        OptionsLastWakeSection = "Last wake",
        OptionsLastWakeUnknown = "No wake event recorded.",
        OptionsLastWakeValue = "Woken by: {0}",
        OptionsLastWakeValueAt = "Woken by: {0} — {1}",
        OptionsLastWakeRefresh = "Refresh",
        OptionsDevicesSection = "Devices allowed to wake the PC",
        OptionsDevicesHint = "Uncheck a device to stop it from waking the PC.",
        OptionsDevicesEmpty = "No configurable devices found.",
        OptionsDevicesReadFailed = "Could not list wake devices.",
        OptionsSomeSettingsFailed = "Some settings could not be saved.",
        AlreadyRunningTitle = "Le Dormeur",
        AlreadyRunningMessage = "Le Dormeur is already running."
    };

    public static readonly UiStrings Spanish = new()
    {
        WindowTitle = "Le Dormeur — brillo + suspensión",
        AppTitle = "Le Dormeur",
        DurationLabel = "Duración antes de la suspensión",
        HoursUnit = "hora(s)",
        MinutesUnit = "minuto(s)",
        BrightnessLabel = "Brillo a quitar durante este tiempo (%)",
        Start = "Iniciar",
        Cancel = "Cancelar",
        Ready = "Listo.",
        LanguageLabel = "Idioma",
        ModeDetecting = "Modo de brillo: detectando...",
        ModeWmi = "Modo de brillo: hardware (WMI) — brillo real del sistema.",
        ModeGamma = "Modo de brillo: gamma por software (pantalla externa / WMI no disponible).",
        ModeGammaUnavailable = "Modo de brillo: gamma no disponible (HDR / controlador / pantalla no compatible).",
        BrightnessControlFailedTitle = "Brillo no disponible",
        BrightnessControlFailedMessage = "No se pudo reducir el brillo. En modo gamma, desactiva HDR o Luz nocturna, comprueba el controlador gráfico o usa una pantalla compatible.",
        BrightnessControlFailedStatus = "Error del control de brillo.",
        InvalidDurationTitle = "Duración no válida",
        InvalidDurationMessage = "La duración debe ser de al menos 1 minuto.",
        Cancelled = "Cancelado. Brillo restaurado.",
        TimeElapsedSleeping = "Tiempo agotado — entrando en suspensión...",
        SleepingPc = "Suspendiendo el PC...",
        SleepFailedTitle = "Error",
        SleepFailedMessage = "No se pudo forzar la suspensión. Comprueba los permisos o la configuración de energía de Windows.",
        SleepFailedStatus = "Error al suspender el PC.",
        SleepOkStatus = "PC suspendido.",
        BrightnessRestoredAfterWake = "Despertar detectado. Brillo restaurado al nivel inicial ({0} %).",
        SleepFailedStatusRestored = "Error al suspender el PC. Brillo restaurado.",
        RunningStatus = "En curso... Brillo: {0} % (inicio {1} % → objetivo {2} %)",
        Remaining = "Tiempo restante: {0}",
        QuitTitle = "Salir",
        QuitMessage = "Hay un temporizador en curso. ¿Cancelar y restaurar el brillo?",
        ExampleHint = "Ejemplo: {0} % en {1} → desde {2} %, el brillo bajará gradualmente hasta unos {3} %, y luego el PC se suspenderá.",
        DurationHoursOnly = "{0} h",
        DurationMinutesOnly = "{0} min",
        DurationHoursAndMinutes = "{0} h {1} min",
        DurationZero = "0 min",
        WarningTitle = "Suspensión inminente",
        WarningCountdown = "Suspensión en {0} s",
        WarningHint = "Aplazar añade 15 minutos. Cancelar detiene el temporizador y restaura el brillo.",
        WarningPostpone = "Aplazar (+15 min)",
        WarningCancel = "Cancelar",
        WarningContinue = "Continuar",
        PostponedStatus = "Suspensión aplazada 15 min. Brillo mantenido, temporizador reiniciado.",
        TrayOpen = "Abrir",
        TrayCancel = "Cancelar temporizador",
        TrayExit = "Salir",
        TrayIdle = "Le Dormeur — listo",
        TrayRunning = "Le Dormeur — restante {0}",
        TrayMinimizedBalloonTitle = "Le Dormeur",
        TrayMinimizedBalloonText = "La aplicación sigue en segundo plano.",
        TrayAutoMode = "Modo automático...",
        TrayAutoArmed = "Le Dormeur — auto {0}",
        AutoModeButton = "Modo auto...",
        AutoModeWindowTitle = "Modo automático",
        AutoModeTitle = "Modo automático",
        AutoModeEnable = "Activar el modo automático",
        AutoModeTime = "Hora de comprobación",
        AutoModeTimeout = "Tiempo de respuesta",
        AutoModeTimeoutUnit = "minuto(s)",
        AutoModeHint = "A la hora elegida, una notificación pregunta si sigues ahí. Si no respondes antes del tiempo límite, el PC se suspende.",
        AutoModeSave = "Guardar",
        AutoModeCancel = "Cerrar",
        AutoModeDisabledStatus = "Modo automático desactivado.",
        AutoModeNextStatus = "Todos los días a las {0} — tiempo de respuesta: {1} min",
        AutoModeArmedStatus = "Modo auto activado — próxima comprobación a las {0}.",
        AutoModeStillHereStatus = "Presencia confirmada. Suspensión automática cancelada por hoy.",
        AutoModeSleepingStatus = "Sin respuesta — suspendiendo (modo auto)...",
        StillThereTitle = "¿Sigues ahí?",
        StillThereMessage = "Confirma tu presencia para evitar la suspensión automática.",
        StillThereCountdown = "Suspensión en {0:D2}:{1:D2}",
        StillThereYes = "Sí, estoy aquí",
        StillThereBalloonTitle = "Le Dormeur",
        StillThereBalloonText = "¿Sigues ahí? Responde para evitar la suspensión.",
        OptionsButton = "Opciones...",
        TrayOptions = "Opciones...",
        OptionsWindowTitle = "Opciones",
        OptionsTitle = "Opciones",
        OptionsPowerPlan = "Plan de energía: {0}",
        OptionsPowerPlanUnknown = "Plan de energía actual",
        OptionsWakeTimersLabel = "Temporizadores de reactivación",
        OptionsOn = "ON",
        OptionsOff = "OFF",
        OptionsWakeTimersHint = "Windows, las actualizaciones y algunas tareas programadas pueden reactivar el PC. Pon OFF para que el PC siga en suspensión hasta una acción manual. Se aplica al plan de energía seleccionado (enchufado y con batería).",
        OptionsWakeTimersOnStatus = "ON — el PC puede reactivarse con temporizadores.",
        OptionsWakeTimersOffStatus = "OFF — el PC permanece en suspensión.",
        OptionsWakeTimersReadFailed = "No se pudo leer el parámetro del plan de energía.",
        OptionsWakeTimersWriteFailed = "No se pudo cambiar el parámetro. Comprueba los permisos de Windows.",
        OptionsWakeTimersWriteFailedAdmin = "No se pudo cambiar el parámetro. Prueba a ejecutar Le Dormeur como administrador.",
        OptionsSave = "Guardar",
        OptionsCancel = "Cerrar",
        OptionsWakeOnLanLabel = "Wake-on-LAN",
        OptionsWakeOnLanHint = "Permite que un paquete mágico de red reactive el PC (adaptadores Ethernet).",
        OptionsWakeOnLanUnsupported = "Wake-on-LAN no es compatible en este PC.",
        OptionsLastWakeSection = "Última reactivación",
        OptionsLastWakeUnknown = "No hay ninguna reactivación registrada.",
        OptionsLastWakeValue = "Reactivado por: {0}",
        OptionsLastWakeValueAt = "Reactivado por: {0} — {1}",
        OptionsLastWakeRefresh = "Actualizar",
        OptionsDevicesSection = "Dispositivos autorizados a reactivar el PC",
        OptionsDevicesHint = "Desmarca un dispositivo para impedir que reactive el PC.",
        OptionsDevicesEmpty = "No se han encontrado dispositivos configurables.",
        OptionsDevicesReadFailed = "No se pudo listar los dispositivos.",
        OptionsSomeSettingsFailed = "Algunos parámetros no se han podido guardar.",
        AlreadyRunningTitle = "Le Dormeur",
        AlreadyRunningMessage = "Le Dormeur ya se está ejecutando."
    };

    public static readonly UiStrings German = new()
    {
        WindowTitle = "Le Dormeur — Helligkeit + Energiesparmodus",
        AppTitle = "Le Dormeur",
        DurationLabel = "Dauer bis zum Energiesparmodus",
        HoursUnit = "Stunde(n)",
        MinutesUnit = "Minute(n)",
        BrightnessLabel = "Zu reduzierende Helligkeit über diese Dauer (%)",
        Start = "Starten",
        Cancel = "Abbrechen",
        Ready = "Bereit.",
        LanguageLabel = "Sprache",
        ModeDetecting = "Helligkeitsmodus: Erkennung...",
        ModeWmi = "Helligkeitsmodus: Hardware (WMI) — echte Systemhelligkeit.",
        ModeGamma = "Helligkeitsmodus: Software-Gamma (externer Bildschirm / WMI nicht verfügbar).",
        ModeGammaUnavailable = "Helligkeitsmodus: Gamma nicht verfügbar (HDR / Treiber / nicht unterstütztes Display).",
        BrightnessControlFailedTitle = "Helligkeit nicht verfügbar",
        BrightnessControlFailedMessage = "Helligkeit konnte nicht reduziert werden. Im Gamma-Modus HDR oder Nachtlicht deaktivieren, Grafiktreiber prüfen oder ein unterstütztes Display verwenden.",
        BrightnessControlFailedStatus = "Helligkeitssteuerung fehlgeschlagen.",
        InvalidDurationTitle = "Ungültige Dauer",
        InvalidDurationMessage = "Die Dauer muss mindestens 1 Minute betragen.",
        Cancelled = "Abgebrochen. Helligkeit wiederhergestellt.",
        TimeElapsedSleeping = "Zeit abgelaufen — wechsle in den Energiesparmodus...",
        SleepingPc = "PC wird in den Energiesparmodus versetzt...",
        SleepFailedTitle = "Fehler",
        SleepFailedMessage = "Energiesparmodus konnte nicht erzwungen werden. Prüfe Berechtigungen oder Windows-Energieeinstellungen.",
        SleepFailedStatus = "Energiesparmodus fehlgeschlagen.",
        SleepOkStatus = "PC im Energiesparmodus.",
        BrightnessRestoredAfterWake = "Aufwachen erkannt. Helligkeit auf Startwert ({0} %) wiederhergestellt.",
        SleepFailedStatusRestored = "Energiesparmodus fehlgeschlagen. Helligkeit wiederhergestellt.",
        RunningStatus = "Läuft... Helligkeit: {0} % (Start {1} % → Ziel {2} %)",
        Remaining = "Verbleibende Zeit: {0}",
        QuitTitle = "Beenden",
        QuitMessage = "Ein Timer läuft. Abbrechen und Helligkeit wiederherstellen?",
        ExampleHint = "Beispiel: {0} % über {1} → ab {2} % sinkt die Helligkeit schrittweise auf etwa {3} %, danach wechselt der PC in den Energiesparmodus.",
        DurationHoursOnly = "{0} Std.",
        DurationMinutesOnly = "{0} Min.",
        DurationHoursAndMinutes = "{0} Std. {1} Min.",
        DurationZero = "0 Min.",
        WarningTitle = "Energiesparmodus steht bevor",
        WarningCountdown = "Energiesparmodus in {0} s",
        WarningHint = "Verschieben fügt 15 Minuten hinzu. Abbrechen stoppt den Timer und stellt die Helligkeit wieder her.",
        WarningPostpone = "Verschieben (+15 Min.)",
        WarningCancel = "Abbrechen",
        WarningContinue = "Weiter",
        PostponedStatus = "Energiesparmodus um 15 Min. verschoben. Helligkeit beibehalten, Timer neu gestartet.",
        TrayOpen = "Öffnen",
        TrayCancel = "Timer abbrechen",
        TrayExit = "Beenden",
        TrayIdle = "Le Dormeur — bereit",
        TrayRunning = "Le Dormeur — verbleibend {0}",
        TrayMinimizedBalloonTitle = "Le Dormeur",
        TrayMinimizedBalloonText = "Die App läuft im Hintergrund weiter.",
        TrayAutoMode = "Automatikmodus...",
        TrayAutoArmed = "Le Dormeur — auto {0}",
        AutoModeButton = "Auto-Modus...",
        AutoModeWindowTitle = "Automatikmodus",
        AutoModeTitle = "Automatikmodus",
        AutoModeEnable = "Automatikmodus aktivieren",
        AutoModeTime = "Prüfzeit",
        AutoModeTimeout = "Antwortfrist",
        AutoModeTimeoutUnit = "Minute(n)",
        AutoModeHint = "Zur gewählten Uhrzeit fragt eine Benachrichtigung, ob du noch da bist. Ohne Antwort vor Ablauf der Frist wechselt der PC in den Energiesparmodus.",
        AutoModeSave = "Speichern",
        AutoModeCancel = "Schließen",
        AutoModeDisabledStatus = "Automatikmodus deaktiviert.",
        AutoModeNextStatus = "Täglich um {0} — Antwortfrist: {1} Min.",
        AutoModeArmedStatus = "Auto-Modus aktiv — nächste Prüfung um {0}.",
        AutoModeStillHereStatus = "Anwesenheit bestätigt. Automatischer Energiesparmodus für heute abgebrochen.",
        AutoModeSleepingStatus = "Keine Antwort — Energiesparmodus (Auto-Modus)...",
        StillThereTitle = "Bist du noch da?",
        StillThereMessage = "Bestätige deine Anwesenheit, um den automatischen Energiesparmodus zu verhindern.",
        StillThereCountdown = "Energiesparmodus in {0:D2}:{1:D2}",
        StillThereYes = "Ja, ich bin da",
        StillThereBalloonTitle = "Le Dormeur",
        StillThereBalloonText = "Bist du noch da? Antworte, um den Energiesparmodus zu verhindern.",
        OptionsButton = "Optionen...",
        TrayOptions = "Optionen...",
        OptionsWindowTitle = "Optionen",
        OptionsTitle = "Optionen",
        OptionsPowerPlan = "Energiesparplan: {0}",
        OptionsPowerPlanUnknown = "Aktueller Energiesparplan",
        OptionsWakeTimersLabel = "Timer zur Reaktivierung",
        OptionsOn = "ON",
        OptionsOff = "OFF",
        OptionsWakeTimersHint = "Windows, Updates und geplante Aufgaben können den PC aufwecken. Mit OFF bleibt der PC im Energiesparmodus, bis du ihn selbst aufweckst. Gilt für den aktuell ausgewählten Energiesparplan (Netzteil und Akku).",
        OptionsWakeTimersOnStatus = "ON — der PC kann durch Timer aufgeweckt werden.",
        OptionsWakeTimersOffStatus = "OFF — der PC bleibt im Energiesparmodus.",
        OptionsWakeTimersReadFailed = "Die Einstellung des Energiesparplans konnte nicht gelesen werden.",
        OptionsWakeTimersWriteFailed = "Die Einstellung konnte nicht geändert werden. Prüfe die Windows-Berechtigungen.",
        OptionsWakeTimersWriteFailedAdmin = "Die Einstellung konnte nicht geändert werden. Versuche, Le Dormeur als Administrator zu starten.",
        OptionsSave = "Speichern",
        OptionsCancel = "Schließen",
        OptionsWakeOnLanLabel = "Wake-on-LAN",
        OptionsWakeOnLanHint = "Erlaubt einem Magic Packet, den PC aufzuwecken (Ethernet-Adapter).",
        OptionsWakeOnLanUnsupported = "Wake-on-LAN wird auf diesem PC nicht unterstützt.",
        OptionsLastWakeSection = "Letztes Aufwachen",
        OptionsLastWakeUnknown = "Kein Aufwachen aufgezeichnet.",
        OptionsLastWakeValue = "Aufgeweckt durch: {0}",
        OptionsLastWakeValueAt = "Aufgeweckt durch: {0} — {1}",
        OptionsLastWakeRefresh = "Aktualisieren",
        OptionsDevicesSection = "Geräte, die den PC aufwecken dürfen",
        OptionsDevicesHint = "Deaktiviere ein Gerät, damit es den PC nicht aufwecken kann.",
        OptionsDevicesEmpty = "Keine konfigurierbaren Geräte gefunden.",
        OptionsDevicesReadFailed = "Geräte konnten nicht aufgelistet werden.",
        OptionsSomeSettingsFailed = "Einige Einstellungen konnten nicht gespeichert werden.",
        AlreadyRunningTitle = "Le Dormeur",
        AlreadyRunningMessage = "Le Dormeur läuft bereits."
    };

    public static readonly UiStrings Italian = new()
    {
        WindowTitle = "Le Dormeur — luminosità + sospensione",
        AppTitle = "Le Dormeur",
        DurationLabel = "Durata prima della sospensione",
        HoursUnit = "ora/e",
        MinutesUnit = "minuto/i",
        BrightnessLabel = "Luminosità da ridurre in questo intervallo (%)",
        Start = "Avvia",
        Cancel = "Annulla",
        Ready = "Pronto.",
        LanguageLabel = "Lingua",
        ModeDetecting = "Modalità luminosità: rilevamento...",
        ModeWmi = "Modalità luminosità: hardware (WMI) — luminosità di sistema reale.",
        ModeGamma = "Modalità luminosità: gamma software (display esterno / WMI non disponibile).",
        ModeGammaUnavailable = "Modalità luminosità: gamma non disponibile (HDR / driver / display non supportato).",
        BrightnessControlFailedTitle = "Luminosità non disponibile",
        BrightnessControlFailedMessage = "Impossibile ridurre la luminosità. In modalità gamma, disattiva HDR o Luce notturna, controlla il driver grafico o usa un display supportato.",
        BrightnessControlFailedStatus = "Controllo luminosità non riuscito.",
        InvalidDurationTitle = "Durata non valida",
        InvalidDurationMessage = "La durata deve essere di almeno 1 minuto.",
        Cancelled = "Annullato. Luminosità ripristinata.",
        TimeElapsedSleeping = "Tempo scaduto — sospensione in corso...",
        SleepingPc = "Sospensione del PC...",
        SleepFailedTitle = "Errore",
        SleepFailedMessage = "Impossibile forzare la sospensione. Controlla i permessi o le impostazioni di alimentazione di Windows.",
        SleepFailedStatus = "Sospensione del PC non riuscita.",
        SleepOkStatus = "PC sospeso.",
        BrightnessRestoredAfterWake = "Riattivazione rilevata. Luminosità ripristinata al livello iniziale ({0} %).",
        SleepFailedStatusRestored = "Sospensione del PC non riuscita. Luminosità ripristinata.",
        RunningStatus = "In corso... Luminosità: {0} % (inizio {1} % → obiettivo {2} %)",
        Remaining = "Tempo rimanente: {0}",
        QuitTitle = "Esci",
        QuitMessage = "Un timer è in corso. Annullare e ripristinare la luminosità?",
        ExampleHint = "Esempio: {0} % su {1} → da {2} %, la luminosità scenderà gradualmente fino a circa {3} %, poi il PC entrerà in sospensione.",
        DurationHoursOnly = "{0} h",
        DurationMinutesOnly = "{0} min",
        DurationHoursAndMinutes = "{0} h {1} min",
        DurationZero = "0 min",
        WarningTitle = "Sospensione imminente",
        WarningCountdown = "Sospensione tra {0} s",
        WarningHint = "Posticipa aggiunge 15 minuti. Annulla ferma il timer e ripristina la luminosità.",
        WarningPostpone = "Posticipa (+15 min)",
        WarningCancel = "Annulla",
        WarningContinue = "Continua",
        PostponedStatus = "Sospensione posticipata di 15 min. Luminosità mantenuta, timer riavviato.",
        TrayOpen = "Apri",
        TrayCancel = "Annulla timer",
        TrayExit = "Esci",
        TrayIdle = "Le Dormeur — pronto",
        TrayRunning = "Le Dormeur — rimanente {0}",
        TrayMinimizedBalloonTitle = "Le Dormeur",
        TrayMinimizedBalloonText = "L'applicazione continua in background.",
        TrayAutoMode = "Modalità automatica...",
        TrayAutoArmed = "Le Dormeur — auto {0}",
        AutoModeButton = "Modo auto...",
        AutoModeWindowTitle = "Modalità automatica",
        AutoModeTitle = "Modalità automatica",
        AutoModeEnable = "Attiva la modalità automatica",
        AutoModeTime = "Ora di verifica",
        AutoModeTimeout = "Tempo di risposta",
        AutoModeTimeoutUnit = "minuto/i",
        AutoModeHint = "All'ora scelta, una notifica chiede se sei ancora lì. Senza risposta entro il tempo limite, il PC entra in sospensione.",
        AutoModeSave = "Salva",
        AutoModeCancel = "Chiudi",
        AutoModeDisabledStatus = "Modalità automatica disattivata.",
        AutoModeNextStatus = "Ogni giorno alle {0} — tempo di risposta: {1} min",
        AutoModeArmedStatus = "Modo auto attivo — prossima verifica alle {0}.",
        AutoModeStillHereStatus = "Presenza confermata. Sospensione automatica annullata per oggi.",
        AutoModeSleepingStatus = "Nessuna risposta — sospensione (modo auto)...",
        StillThereTitle = "Sei ancora lì?",
        StillThereMessage = "Conferma la tua presenza per evitare la sospensione automatica.",
        StillThereCountdown = "Sospensione tra {0:D2}:{1:D2}",
        StillThereYes = "Sì, sono qui",
        StillThereBalloonTitle = "Le Dormeur",
        StillThereBalloonText = "Sei ancora lì? Rispondi per evitare la sospensione.",
        OptionsButton = "Opzioni...",
        TrayOptions = "Opzioni...",
        OptionsWindowTitle = "Opzioni",
        OptionsTitle = "Opzioni",
        OptionsPowerPlan = "Piano di alimentazione: {0}",
        OptionsPowerPlanUnknown = "Piano di alimentazione attuale",
        OptionsWakeTimersLabel = "Timer di riattivazione",
        OptionsOn = "ON",
        OptionsOff = "OFF",
        OptionsWakeTimersHint = "Windows, gli aggiornamenti e alcune attività pianificate possono riattivare il PC. Imposta OFF perché il PC resti in sospensione fino a un’azione manuale. Si applica al piano di alimentazione selezionato (alimentazione e batteria).",
        OptionsWakeTimersOnStatus = "ON — il PC può essere riattivato dai timer.",
        OptionsWakeTimersOffStatus = "OFF — il PC resta in sospensione.",
        OptionsWakeTimersReadFailed = "Impossibile leggere l’impostazione del piano di alimentazione.",
        OptionsWakeTimersWriteFailed = "Impossibile modificare l’impostazione. Controlla i permessi di Windows.",
        OptionsWakeTimersWriteFailedAdmin = "Impossibile modificare l’impostazione. Prova ad avviare Le Dormeur come amministratore.",
        OptionsSave = "Salva",
        OptionsCancel = "Chiudi",
        OptionsWakeOnLanLabel = "Wake-on-LAN",
        OptionsWakeOnLanHint = "Consente a un magic packet di rete di riattivare il PC (schede Ethernet).",
        OptionsWakeOnLanUnsupported = "Wake-on-LAN non supportato su questo PC.",
        OptionsLastWakeSection = "Ultima riattivazione",
        OptionsLastWakeUnknown = "Nessuna riattivazione registrata.",
        OptionsLastWakeValue = "Riattivato da: {0}",
        OptionsLastWakeValueAt = "Riattivato da: {0} — {1}",
        OptionsLastWakeRefresh = "Aggiorna",
        OptionsDevicesSection = "Dispositivi autorizzati a riattivare il PC",
        OptionsDevicesHint = "Deseleziona un dispositivo per impedirgli di riattivare il PC.",
        OptionsDevicesEmpty = "Nessun dispositivo configurabile trovato.",
        OptionsDevicesReadFailed = "Impossibile elencare i dispositivi.",
        OptionsSomeSettingsFailed = "Alcune impostazioni non sono state salvate.",
        AlreadyRunningTitle = "Le Dormeur",
        AlreadyRunningMessage = "Le Dormeur è già in esecuzione."
    };

    public static readonly UiStrings Portuguese = new()
    {
        WindowTitle = "Le Dormeur — brilho + suspensão",
        AppTitle = "Le Dormeur",
        DurationLabel = "Duração antes da suspensão",
        HoursUnit = "hora(s)",
        MinutesUnit = "minuto(s)",
        BrightnessLabel = "Brilho a reduzir durante este período (%)",
        Start = "Iniciar",
        Cancel = "Cancelar",
        Ready = "Pronto.",
        LanguageLabel = "Idioma",
        ModeDetecting = "Modo de brilho: a detetar...",
        ModeWmi = "Modo de brilho: hardware (WMI) — brilho real do sistema.",
        ModeGamma = "Modo de brilho: gama por software (ecrã externo / WMI indisponível).",
        ModeGammaUnavailable = "Modo de brilho: gama indisponível (HDR / controlador / ecrã não suportado).",
        BrightnessControlFailedTitle = "Brilho indisponível",
        BrightnessControlFailedMessage = "Não foi possível reduzir o brilho. No modo gama, desative o HDR ou a Luz noturna, verifique o controlador gráfico ou use um ecrã compatível.",
        BrightnessControlFailedStatus = "Falha no controlo de brilho.",
        InvalidDurationTitle = "Duração inválida",
        InvalidDurationMessage = "A duração deve ser de pelo menos 1 minuto.",
        Cancelled = "Cancelado. Brilho restaurado.",
        TimeElapsedSleeping = "Tempo esgotado — a suspender...",
        SleepingPc = "A suspender o PC...",
        SleepFailedTitle = "Erro",
        SleepFailedMessage = "Não foi possível forçar a suspensão. Verifique permissões ou as definições de energia do Windows.",
        SleepFailedStatus = "Falha ao suspender o PC.",
        SleepOkStatus = "PC suspenso.",
        BrightnessRestoredAfterWake = "Reativação detetada. Brilho restaurado para o nível inicial ({0} %).",
        SleepFailedStatusRestored = "Falha ao suspender o PC. Brilho restaurado.",
        RunningStatus = "Em curso... Brilho: {0} % (início {1} % → alvo {2} %)",
        Remaining = "Tempo restante: {0}",
        QuitTitle = "Sair",
        QuitMessage = "Um temporizador está em curso. Cancelar e restaurar o brilho?",
        ExampleHint = "Exemplo: {0} % em {1} → a partir de {2} %, o brilho descerá gradualmente até cerca de {3} %, e depois o PC entrará em suspensão.",
        DurationHoursOnly = "{0} h",
        DurationMinutesOnly = "{0} min",
        DurationHoursAndMinutes = "{0} h {1} min",
        DurationZero = "0 min",
        WarningTitle = "Suspensão iminente",
        WarningCountdown = "Suspensão em {0} s",
        WarningHint = "Adiar acrescenta 15 minutos. Cancelar para o temporizador e restaura o brilho.",
        WarningPostpone = "Adiar (+15 min)",
        WarningCancel = "Cancelar",
        WarningContinue = "Continuar",
        PostponedStatus = "Suspensão adiada 15 min. Brilho mantido, temporizador reiniciado.",
        TrayOpen = "Abrir",
        TrayCancel = "Cancelar temporizador",
        TrayExit = "Sair",
        TrayIdle = "Le Dormeur — pronto",
        TrayRunning = "Le Dormeur — restante {0}",
        TrayMinimizedBalloonTitle = "Le Dormeur",
        TrayMinimizedBalloonText = "A aplicação continua em segundo plano.",
        TrayAutoMode = "Modo automático...",
        TrayAutoArmed = "Le Dormeur — auto {0}",
        AutoModeButton = "Modo auto...",
        AutoModeWindowTitle = "Modo automático",
        AutoModeTitle = "Modo automático",
        AutoModeEnable = "Ativar o modo automático",
        AutoModeTime = "Hora de verificação",
        AutoModeTimeout = "Tempo de resposta",
        AutoModeTimeoutUnit = "minuto(s)",
        AutoModeHint = "À hora escolhida, uma notificação pergunta se ainda está aí. Sem resposta antes do limite, o PC entra em suspensão.",
        AutoModeSave = "Guardar",
        AutoModeCancel = "Fechar",
        AutoModeDisabledStatus = "Modo automático desativado.",
        AutoModeNextStatus = "Todos os dias às {0} — tempo de resposta: {1} min",
        AutoModeArmedStatus = "Modo auto ativo — próxima verificação às {0}.",
        AutoModeStillHereStatus = "Presença confirmada. Suspensão automática cancelada para hoje.",
        AutoModeSleepingStatus = "Sem resposta — a suspender (modo auto)...",
        StillThereTitle = "Ainda está aí?",
        StillThereMessage = "Confirme a sua presença para evitar a suspensão automática.",
        StillThereCountdown = "Suspensão em {0:D2}:{1:D2}",
        StillThereYes = "Sim, estou aqui",
        StillThereBalloonTitle = "Le Dormeur",
        StillThereBalloonText = "Ainda está aí? Responda para evitar a suspensão.",
        OptionsButton = "Opções...",
        TrayOptions = "Opções...",
        OptionsWindowTitle = "Opções",
        OptionsTitle = "Opções",
        OptionsPowerPlan = "Plano de energia: {0}",
        OptionsPowerPlanUnknown = "Plano de energia atual",
        OptionsWakeTimersLabel = "Temporizadores de reativação",
        OptionsOn = "ON",
        OptionsOff = "OFF",
        OptionsWakeTimersHint = "O Windows, as atualizações e algumas tarefas agendadas podem reativar o PC. Ponha OFF para o PC permanecer em suspensão até uma ação manual. Aplica-se ao plano de energia selecionado (ligado à corrente e em bateria).",
        OptionsWakeTimersOnStatus = "ON — o PC pode ser reativado por temporizadores.",
        OptionsWakeTimersOffStatus = "OFF — o PC permanece em suspensão.",
        OptionsWakeTimersReadFailed = "Não foi possível ler a definição do plano de energia.",
        OptionsWakeTimersWriteFailed = "Não foi possível alterar a definição. Verifique as permissões do Windows.",
        OptionsWakeTimersWriteFailedAdmin = "Não foi possível alterar a definição. Tente executar o Le Dormeur como administrador.",
        OptionsSave = "Guardar",
        OptionsCancel = "Fechar",
        OptionsWakeOnLanLabel = "Wake-on-LAN",
        OptionsWakeOnLanHint = "Permite que um pacote mágico de rede reative o PC (adaptadores Ethernet).",
        OptionsWakeOnLanUnsupported = "Wake-on-LAN não é suportado neste PC.",
        OptionsLastWakeSection = "Última reativação",
        OptionsLastWakeUnknown = "Nenhuma reativação registada.",
        OptionsLastWakeValue = "Reativado por: {0}",
        OptionsLastWakeValueAt = "Reativado por: {0} — {1}",
        OptionsLastWakeRefresh = "Atualizar",
        OptionsDevicesSection = "Dispositivos autorizados a reativar o PC",
        OptionsDevicesHint = "Desmarque um dispositivo para o impedir de reativar o PC.",
        OptionsDevicesEmpty = "Nenhum dispositivo configurável encontrado.",
        OptionsDevicesReadFailed = "Não foi possível listar os dispositivos.",
        OptionsSomeSettingsFailed = "Algumas definições não puderam ser guardadas.",
        AlreadyRunningTitle = "Le Dormeur",
        AlreadyRunningMessage = "O Le Dormeur já está em execução."
    };

    public static readonly UiStrings Dutch = new()
    {
        WindowTitle = "Le Dormeur — helderheid + slaapstand",
        AppTitle = "Le Dormeur",
        DurationLabel = "Duur vóór slaapstand",
        HoursUnit = "uur",
        MinutesUnit = "minu(u)t(en)",
        BrightnessLabel = "Helderheid te verlagen over deze duur (%)",
        Start = "Starten",
        Cancel = "Annuleren",
        Ready = "Klaar.",
        LanguageLabel = "Taal",
        ModeDetecting = "Helderheidsmodus: detecteren...",
        ModeWmi = "Helderheidsmodus: hardware (WMI) — echte systeemhelderheid.",
        ModeGamma = "Helderheidsmodus: software-gamma (extern scherm / WMI niet beschikbaar).",
        ModeGammaUnavailable = "Helderheidsmodus: gamma niet beschikbaar (HDR / stuurprogramma / niet-ondersteund scherm).",
        BrightnessControlFailedTitle = "Helderheid niet beschikbaar",
        BrightnessControlFailedMessage = "Helderheid kon niet worden verlaagd. Schakel in gammamodus HDR of Nachtlicht uit, controleer het grafische stuurprogramma of gebruik een ondersteund scherm.",
        BrightnessControlFailedStatus = "Helderheidsregeling mislukt.",
        InvalidDurationTitle = "Ongeldige duur",
        InvalidDurationMessage = "De duur moet minstens 1 minuut zijn.",
        Cancelled = "Geannuleerd. Helderheid hersteld.",
        TimeElapsedSleeping = "Tijd is om — naar de slaapstand...",
        SleepingPc = "Pc in slaapstand zetten...",
        SleepFailedTitle = "Fout",
        SleepFailedMessage = "Slaapstand kon niet worden afgedwongen. Controleer rechten of Windows-energie-instellingen.",
        SleepFailedStatus = "Slaapstand mislukt.",
        SleepOkStatus = "Pc in slaapstand gezet.",
        BrightnessRestoredAfterWake = "Ontwaken gedetecteerd. Helderheid hersteld naar startniveau ({0} %).",
        SleepFailedStatusRestored = "Slaapstand mislukt. Helderheid hersteld.",
        RunningStatus = "Bezig... Helderheid: {0} % (start {1} % → doel {2} %)",
        Remaining = "Resterende tijd: {0}",
        QuitTitle = "Afsluiten",
        QuitMessage = "Er loopt een timer. Annuleren en helderheid herstellen?",
        ExampleHint = "Voorbeeld: {0} % over {1} → vanaf {2} % daalt de helderheid geleidelijk tot ongeveer {3} %, daarna gaat de pc in slaapstand.",
        DurationHoursOnly = "{0} u",
        DurationMinutesOnly = "{0} min",
        DurationHoursAndMinutes = "{0} u {1} min",
        DurationZero = "0 min",
        WarningTitle = "Slaapstand nadert",
        WarningCountdown = "Slaapstand over {0} s",
        WarningHint = "Uitstellen voegt 15 minuten toe. Annuleren stopt de timer en herstelt de helderheid.",
        WarningPostpone = "Uitstellen (+15 min)",
        WarningCancel = "Annuleren",
        WarningContinue = "Doorgaan",
        PostponedStatus = "Slaapstand 15 min uitgesteld. Helderheid behouden, timer opnieuw gestart.",
        TrayOpen = "Openen",
        TrayCancel = "Timer annuleren",
        TrayExit = "Afsluiten",
        TrayIdle = "Le Dormeur — klaar",
        TrayRunning = "Le Dormeur — resterend {0}",
        TrayMinimizedBalloonTitle = "Le Dormeur",
        TrayMinimizedBalloonText = "De app blijft op de achtergrond actief.",
        TrayAutoMode = "Automatische modus...",
        TrayAutoArmed = "Le Dormeur — auto {0}",
        AutoModeButton = "Auto-modus...",
        AutoModeWindowTitle = "Automatische modus",
        AutoModeTitle = "Automatische modus",
        AutoModeEnable = "Automatische modus inschakelen",
        AutoModeTime = "Controletijd",
        AutoModeTimeout = "Reactietijd",
        AutoModeTimeoutUnit = "minu(u)t(en)",
        AutoModeHint = "Op het gekozen tijdstip vraagt een melding of je er nog bent. Zonder antwoord vóór de limiet gaat de pc in slaapstand.",
        AutoModeSave = "Opslaan",
        AutoModeCancel = "Sluiten",
        AutoModeDisabledStatus = "Automatische modus uitgeschakeld.",
        AutoModeNextStatus = "Elke dag om {0} — reactietijd: {1} min",
        AutoModeArmedStatus = "Auto-modus aan — volgende controle om {0}.",
        AutoModeStillHereStatus = "Aanwezigheid bevestigd. Automatische slaapstand voor vandaag geannuleerd.",
        AutoModeSleepingStatus = "Geen antwoord — slaapstand (auto-modus)...",
        StillThereTitle = "Ben je er nog?",
        StillThereMessage = "Bevestig je aanwezigheid om automatische slaapstand te voorkomen.",
        StillThereCountdown = "Slaapstand over {0:D2}:{1:D2}",
        StillThereYes = "Ja, ik ben er",
        StillThereBalloonTitle = "Le Dormeur",
        StillThereBalloonText = "Ben je er nog? Antwoord om slaapstand te voorkomen.",
        OptionsButton = "Opties...",
        TrayOptions = "Opties...",
        OptionsWindowTitle = "Opties",
        OptionsTitle = "Opties",
        OptionsPowerPlan = "Energieplan: {0}",
        OptionsPowerPlanUnknown = "Huidig energieplan",
        OptionsWakeTimersLabel = "Timers voor ontwaken",
        OptionsOn = "ON",
        OptionsOff = "OFF",
        OptionsWakeTimersHint = "Windows, updates en geplande taken kunnen de pc wekken. Zet dit op OFF zodat de pc in slaapstand blijft tot je hem zelf wekt. Geldt voor het geselecteerde energieplan (netstroom en accu).",
        OptionsWakeTimersOnStatus = "ON — de pc kan door timers worden gewekt.",
        OptionsWakeTimersOffStatus = "OFF — de pc blijft in slaapstand.",
        OptionsWakeTimersReadFailed = "Kon de instelling van het energieplan niet lezen.",
        OptionsWakeTimersWriteFailed = "Kon de instelling niet wijzigen. Controleer de Windows-rechten.",
        OptionsWakeTimersWriteFailedAdmin = "Kon de instelling niet wijzigen. Probeer Le Dormeur als administrator te starten.",
        OptionsSave = "Opslaan",
        OptionsCancel = "Sluiten",
        OptionsWakeOnLanLabel = "Wake-on-LAN",
        OptionsWakeOnLanHint = "Laat een magisch netwerkpakket de pc wekken (Ethernet-adapters).",
        OptionsWakeOnLanUnsupported = "Wake-on-LAN wordt op deze pc niet ondersteund.",
        OptionsLastWakeSection = "Laatste ontwaken",
        OptionsLastWakeUnknown = "Geen ontwaken geregistreerd.",
        OptionsLastWakeValue = "Gewekt door: {0}",
        OptionsLastWakeValueAt = "Gewekt door: {0} — {1}",
        OptionsLastWakeRefresh = "Vernieuwen",
        OptionsDevicesSection = "Apparaten die de pc mogen wekken",
        OptionsDevicesHint = "Vink een apparaat uit om te voorkomen dat het de pc wekt.",
        OptionsDevicesEmpty = "Geen configureerbare apparaten gevonden.",
        OptionsDevicesReadFailed = "Apparaten konden niet worden opgesomd.",
        OptionsSomeSettingsFailed = "Sommige instellingen konden niet worden opgeslagen.",
        AlreadyRunningTitle = "Le Dormeur",
        AlreadyRunningMessage = "Le Dormeur is al gestart."
    };

    public static readonly UiStrings Russian = new()
    {
        WindowTitle = "Le Dormeur — яркость + сон",
        AppTitle = "Le Dormeur",
        DurationLabel = "Время до перехода в сон",
        HoursUnit = "ч",
        MinutesUnit = "мин",
        BrightnessLabel = "Снижение яркости за это время (%)",
        Start = "Старт",
        Cancel = "Отмена",
        Ready = "Готово.",
        LanguageLabel = "Язык",
        ModeDetecting = "Режим яркости: определение...",
        ModeWmi = "Режим яркости: оборудование (WMI) — системная яркость.",
        ModeGamma = "Режим яркости: программная гамма (внешний монитор / WMI недоступен).",
        ModeGammaUnavailable = "Режим яркости: гамма недоступна (HDR / драйвер / неподдерживаемый дисплей).",
        BrightnessControlFailedTitle = "Яркость недоступна",
        BrightnessControlFailedMessage = "Не удалось снизить яркость. В режиме гаммы отключите HDR или ночной свет, проверьте графический драйвер или используйте поддерживаемый дисплей.",
        BrightnessControlFailedStatus = "Ошибка управления яркостью.",
        InvalidDurationTitle = "Неверная длительность",
        InvalidDurationMessage = "Длительность должна быть не менее 1 минуты.",
        Cancelled = "Отменено. Яркость восстановлена.",
        TimeElapsedSleeping = "Время вышло — переход в сон...",
        SleepingPc = "Перевод ПК в спящий режим...",
        SleepFailedTitle = "Ошибка",
        SleepFailedMessage = "Не удалось принудительно перевести ПК в сон. Проверьте права или параметры питания Windows.",
        SleepFailedStatus = "Не удалось перевести ПК в сон.",
        SleepOkStatus = "ПК переведён в спящий режим.",
        BrightnessRestoredAfterWake = "Обнаружено пробуждение. Яркость восстановлена до начального уровня ({0} %).",
        SleepFailedStatusRestored = "Не удалось перевести ПК в сон. Яркость восстановлена.",
        RunningStatus = "Выполняется... Яркость: {0} % (старт {1} % → цель {2} %)",
        Remaining = "Осталось: {0}",
        QuitTitle = "Выход",
        QuitMessage = "Таймер запущен. Отменить и восстановить яркость?",
        ExampleHint = "Пример: {0} % за {1} → от {2} % яркость постепенно снизится примерно до {3} %, затем ПК перейдёт в сон.",
        DurationHoursOnly = "{0} ч",
        DurationMinutesOnly = "{0} мин",
        DurationHoursAndMinutes = "{0} ч {1} мин",
        DurationZero = "0 мин",
        WarningTitle = "Скоро переход в сон",
        WarningCountdown = "Сон через {0} с",
        WarningHint = "Отложить добавляет 15 минут. Отмена останавливает таймер и восстанавливает яркость.",
        WarningPostpone = "Отложить (+15 мин)",
        WarningCancel = "Отмена",
        WarningContinue = "Продолжить",
        PostponedStatus = "Сон отложен на 15 мин. Яркость сохранена, таймер перезапущен.",
        TrayOpen = "Открыть",
        TrayCancel = "Отменить таймер",
        TrayExit = "Выход",
        TrayIdle = "Le Dormeur — готов",
        TrayRunning = "Le Dormeur — осталось {0}",
        TrayMinimizedBalloonTitle = "Le Dormeur",
        TrayMinimizedBalloonText = "Приложение продолжает работать в фоне.",
        TrayAutoMode = "Автоматический режим...",
        TrayAutoArmed = "Le Dormeur — авто {0}",
        AutoModeButton = "Авторежим...",
        AutoModeWindowTitle = "Автоматический режим",
        AutoModeTitle = "Автоматический режим",
        AutoModeEnable = "Включить автоматический режим",
        AutoModeTime = "Время проверки",
        AutoModeTimeout = "Время на ответ",
        AutoModeTimeoutUnit = "мин",
        AutoModeHint = "В выбранное время уведомление спросит, на месте ли вы. Без ответа до истечения срока ПК перейдёт в сон.",
        AutoModeSave = "Сохранить",
        AutoModeCancel = "Закрыть",
        AutoModeDisabledStatus = "Автоматический режим выключен.",
        AutoModeNextStatus = "Каждый день в {0} — время на ответ: {1} мин",
        AutoModeArmedStatus = "Авторежим включён — следующая проверка в {0}.",
        AutoModeStillHereStatus = "Присутствие подтверждено. Автосон на сегодня отменён.",
        AutoModeSleepingStatus = "Нет ответа — переход в сон (авторежим)...",
        StillThereTitle = "Вы ещё здесь?",
        StillThereMessage = "Подтвердите присутствие, чтобы избежать автоматического сна.",
        StillThereCountdown = "Сон через {0:D2}:{1:D2}",
        StillThereYes = "Да, я здесь",
        StillThereBalloonTitle = "Le Dormeur",
        StillThereBalloonText = "Вы ещё здесь? Ответьте, чтобы избежать сна.",
        OptionsButton = "Параметры...",
        TrayOptions = "Параметры...",
        OptionsWindowTitle = "Параметры",
        OptionsTitle = "Параметры",
        OptionsPowerPlan = "Схема питания: {0}",
        OptionsPowerPlanUnknown = "Текущая схема питания",
        OptionsWakeTimersLabel = "Таймеры пробуждения",
        OptionsOn = "ON",
        OptionsOff = "OFF",
        OptionsWakeTimersHint = "Windows, обновления и некоторые задания могут разбудить ПК. Выберите OFF, чтобы ПК оставался в сне до ручного пробуждения. Применяется к выбранной схеме питания (сеть и батарея).",
        OptionsWakeTimersOnStatus = "ON — ПК может быть разбужен таймерами.",
        OptionsWakeTimersOffStatus = "OFF — ПК остаётся в спящем режиме.",
        OptionsWakeTimersReadFailed = "Не удалось прочитать параметр схемы питания.",
        OptionsWakeTimersWriteFailed = "Не удалось изменить параметр. Проверьте права Windows.",
        OptionsWakeTimersWriteFailedAdmin = "Не удалось изменить параметр. Попробуйте запустить Le Dormeur от имени администратора.",
        OptionsSave = "Сохранить",
        OptionsCancel = "Закрыть",
        OptionsWakeOnLanLabel = "Wake-on-LAN",
        OptionsWakeOnLanHint = "Разрешает разбудить ПК магическим сетевым пакетом (адаптеры Ethernet).",
        OptionsWakeOnLanUnsupported = "Wake-on-LAN не поддерживается на этом ПК.",
        OptionsLastWakeSection = "Последнее пробуждение",
        OptionsLastWakeUnknown = "Пробуждений не записано.",
        OptionsLastWakeValue = "Разбужен: {0}",
        OptionsLastWakeValueAt = "Разбужен: {0} — {1}",
        OptionsLastWakeRefresh = "Обновить",
        OptionsDevicesSection = "Устройства, которым разрешено будить ПК",
        OptionsDevicesHint = "Снимите флажок, чтобы устройство не могло разбудить ПК.",
        OptionsDevicesEmpty = "Настраиваемых устройств не найдено.",
        OptionsDevicesReadFailed = "Не удалось получить список устройств.",
        OptionsSomeSettingsFailed = "Некоторые параметры не удалось сохранить.",
        AlreadyRunningTitle = "Le Dormeur",
        AlreadyRunningMessage = "Le Dormeur уже запущен."
    };

    public static readonly UiStrings Chinese = new()
    {
        WindowTitle = "Le Dormeur — 亮度 + 睡眠",
        AppTitle = "Le Dormeur",
        DurationLabel = "进入睡眠前的时长",
        HoursUnit = "小时",
        MinutesUnit = "分钟",
        BrightnessLabel = "在此时间内降低的亮度 (%)",
        Start = "开始",
        Cancel = "取消",
        Ready = "就绪。",
        LanguageLabel = "语言",
        ModeDetecting = "亮度模式：检测中...",
        ModeWmi = "亮度模式：硬件 (WMI) — 系统真实亮度。",
        ModeGamma = "亮度模式：软件伽马（外接显示器 / WMI 不可用）。",
        ModeGammaUnavailable = "亮度模式：伽马不可用（HDR / 驱动 / 不支持的显示器）。",
        BrightnessControlFailedTitle = "亮度不可用",
        BrightnessControlFailedMessage = "无法降低亮度。在伽马模式下，请关闭 HDR 或夜间模式，检查显卡驱动，或使用受支持的显示器。",
        BrightnessControlFailedStatus = "亮度控制失败。",
        InvalidDurationTitle = "时长无效",
        InvalidDurationMessage = "时长至少需要 1 分钟。",
        Cancelled = "已取消。亮度已恢复。",
        TimeElapsedSleeping = "时间到 — 正在进入睡眠...",
        SleepingPc = "正在使电脑进入睡眠...",
        SleepFailedTitle = "错误",
        SleepFailedMessage = "无法强制进入睡眠。请检查权限或 Windows 电源设置。",
        SleepFailedStatus = "使电脑进入睡眠失败。",
        SleepOkStatus = "电脑已进入睡眠。",
        BrightnessRestoredAfterWake = "检测到唤醒。亮度已恢复到起始水平 ({0} %)。",
        SleepFailedStatusRestored = "使电脑进入睡眠失败。亮度已恢复。",
        RunningStatus = "进行中... 亮度：{0} %（起始 {1} % → 目标 {2} %）",
        Remaining = "剩余时间：{0}",
        QuitTitle = "退出",
        QuitMessage = "计时器正在运行。是否取消并恢复亮度？",
        ExampleHint = "示例：在 {1} 内降低 {0} % → 从 {2} % 起，亮度将逐渐降至约 {3} %，然后电脑进入睡眠。",
        DurationHoursOnly = "{0} 小时",
        DurationMinutesOnly = "{0} 分钟",
        DurationHoursAndMinutes = "{0} 小时 {1} 分钟",
        DurationZero = "0 分钟",
        WarningTitle = "即将进入睡眠",
        WarningCountdown = "{0} 秒后进入睡眠",
        WarningHint = "推迟将增加 15 分钟。取消会停止计时器并恢复亮度。",
        WarningPostpone = "推迟（+15 分钟）",
        WarningCancel = "取消",
        WarningContinue = "继续",
        PostponedStatus = "睡眠已推迟 15 分钟。亮度保持不变，计时器已重新启动。",
        TrayOpen = "打开",
        TrayCancel = "取消计时器",
        TrayExit = "退出",
        TrayIdle = "Le Dormeur — 就绪",
        TrayRunning = "Le Dormeur — 剩余 {0}",
        TrayMinimizedBalloonTitle = "Le Dormeur",
        TrayMinimizedBalloonText = "应用仍在后台运行。",
        TrayAutoMode = "自动模式...",
        TrayAutoArmed = "Le Dormeur — 自动 {0}",
        AutoModeButton = "自动模式...",
        AutoModeWindowTitle = "自动模式",
        AutoModeTitle = "自动模式",
        AutoModeEnable = "启用自动模式",
        AutoModeTime = "检查时间",
        AutoModeTimeout = "响应时限",
        AutoModeTimeoutUnit = "分钟",
        AutoModeHint = "在设定时间会弹出通知询问您是否仍在。若在时限内未响应，电脑将进入睡眠。",
        AutoModeSave = "保存",
        AutoModeCancel = "关闭",
        AutoModeDisabledStatus = "自动模式已关闭。",
        AutoModeNextStatus = "每天 {0} — 响应时限：{1} 分钟",
        AutoModeArmedStatus = "自动模式已开启 — 下次检查：{0}。",
        AutoModeStillHereStatus = "已确认在场。今日自动睡眠已取消。",
        AutoModeSleepingStatus = "无响应 — 正在进入睡眠（自动模式）...",
        StillThereTitle = "您还在吗？",
        StillThereMessage = "请确认您仍在，以避免自动睡眠。",
        StillThereCountdown = "{0:D2}:{1:D2} 后进入睡眠",
        StillThereYes = "是的，我在",
        StillThereBalloonTitle = "Le Dormeur",
        StillThereBalloonText = "您还在吗？请回复以避免睡眠。",
        OptionsButton = "选项...",
        TrayOptions = "选项...",
        OptionsWindowTitle = "选项",
        OptionsTitle = "选项",
        OptionsPowerPlan = "电源计划：{0}",
        OptionsPowerPlanUnknown = "当前电源计划",
        OptionsWakeTimersLabel = "唤醒定时器",
        OptionsOn = "ON",
        OptionsOff = "OFF",
        OptionsWakeTimersHint = "Windows、更新和某些计划任务可能会唤醒电脑。设为 OFF 后，电脑将保持睡眠直到你手动唤醒。应用于当前所选电源计划（接通电源和使用电池）。",
        OptionsWakeTimersOnStatus = "ON — 电脑可由定时器唤醒。",
        OptionsWakeTimersOffStatus = "OFF — 电脑保持睡眠。",
        OptionsWakeTimersReadFailed = "无法读取电源计划设置。",
        OptionsWakeTimersWriteFailed = "无法更改设置。请检查 Windows 权限。",
        OptionsWakeTimersWriteFailedAdmin = "无法更改设置。请尝试以管理员身份运行 Le Dormeur。",
        OptionsSave = "保存",
        OptionsCancel = "关闭",
        OptionsWakeOnLanLabel = "Wake-on-LAN",
        OptionsWakeOnLanHint = "允许魔术网络数据包唤醒电脑（以太网适配器）。",
        OptionsWakeOnLanUnsupported = "此电脑不支持 Wake-on-LAN。",
        OptionsLastWakeSection = "上次唤醒",
        OptionsLastWakeUnknown = "没有记录到唤醒事件。",
        OptionsLastWakeValue = "唤醒来源：{0}",
        OptionsLastWakeValueAt = "唤醒来源：{0} — {1}",
        OptionsLastWakeRefresh = "刷新",
        OptionsDevicesSection = "允许唤醒电脑的设备",
        OptionsDevicesHint = "取消勾选可阻止该设备唤醒电脑。",
        OptionsDevicesEmpty = "未找到可配置的设备。",
        OptionsDevicesReadFailed = "无法列出设备。",
        OptionsSomeSettingsFailed = "部分设置未能保存。",
        AlreadyRunningTitle = "Le Dormeur",
        AlreadyRunningMessage = "Le Dormeur 已在运行。"
    };
}
